# Generated by Django 3.0.7 on 2020-06-12 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20200611_1359'),
        ('posting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posting',
            name='users',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.Users'),
        ),
    ]
